version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dispatcher
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
